/**
 * Inline CSS for the FeatureTable. The wrapper id (`#${tableId}_wrapper`)
 * is generated by DataTables, so the styles are scoped per-table — multiple
 * FeatureTable instances on the same page don't clobber each other.
 *
 * Lifted out of the component so the JSX stays scannable; the function form
 * is needed because the selectors interpolate `tableId`.
 */
export const buildTableStyles = (tableId) => `
  #${tableId}_wrapper, #${tableId}_wrapper th, #${tableId}_wrapper td{font-family:Inter,sans-serif;}
  #${tableId}_wrapper th{font-weight:600;}
  .row-selected{background-color:rgba(99,102,241,.12)!important;}
  #${tableId}_wrapper .dt-buttons{display:none!important;}

  /* Hide the built-in filter; we provide our own toolbar */
  #${tableId}_wrapper .dataTables_filter{display:none!important;}

  /* Custom toolbar */
  #${tableId}-toolbar{
    display:flex; align-items:center; gap:.5rem; margin:0 0 .5rem 0;
    font-size:12px;
  }
  #${tableId}-toolbar select{
    height:28px; padding:2px 6px;
  }
  #${tableId}-toolbar input{
    height:28px; padding:2px 6px; min-width:220px;
  }
  #${tableId}-toolbar button{
    height:28px; padding:2px 8px;
  }

  /* Search guide tooltip */
  .search-guide-wrapper{
    position:relative; display:inline-flex; align-items:center;
  }
  .search-guide-icon{
    display:inline-flex; align-items:center; justify-content:center;
    width:18px; height:18px; border-radius:50%;
    border:1.5px solid #9ca3af; color:#6b7280;
    font-size:11px; font-weight:700; font-style:italic;
    font-family:Georgia,serif; cursor:help; user-select:none;
    line-height:1;
  }
  .search-guide-wrapper:hover .search-guide-icon{
    border-color:#6366f1; color:#6366f1;
  }
  .search-guide-tooltip{
    display:none; position:absolute; right:0; top:calc(100% + 8px);
    width:310px; padding:10px 12px;
    background:#1f2937; color:#f3f4f6; border-radius:8px;
    font-size:11.5px; line-height:1.5; z-index:9999;
    box-shadow:0 4px 12px rgba(0,0,0,.25);
  }
  .search-guide-tooltip::before{
    content:''; position:absolute; right:4px; bottom:100%;
    border:6px solid transparent; border-bottom-color:#1f2937;
  }
  .search-guide-wrapper:hover .search-guide-tooltip{
    display:block;
  }
  .search-guide-tooltip hr{
    border:none; border-top:1px solid #4b5563; margin:6px 0;
  }
  .search-guide-tooltip p{
    margin:4px 0;
  }
  .search-guide-tooltip ul{
    margin:2px 0 4px 16px; padding:0;
  }
  .search-guide-tooltip li{
    margin:1px 0;
  }
  .search-guide-tooltip code{
    background:#374151; padding:1px 4px; border-radius:3px;
    font-size:11px;
  }
  .search-guide-tooltip em{
    color:#9ca3af;
  }
`;
