upstream fe { server webmap_frontend_prod:5021; }
#upstream be { server backend:8090; }
upstream afe { server authentification_frontend:5022; }

server {
  listen 80;

  # /authentification/backend/... -> backend (prefix strip)
 # location ^~ /authentification/backend/ {
  #  rewrite ^/authentification/backend/(.*)$ /$1 break;
   # proxy_pass http://be;
  #  proxy_set_header Host $host;
  #  proxy_set_header X-Real-IP $remote_addr;
  #  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #  proxy_set_header X-Forwarded-Proto $scheme;
 # }

  # /authentification/... -> authentication frontend (prefix strip)
  location ^~ /authentification/ {
    rewrite ^/authentification/(.*)$ /$1 break;
    proxy_pass http://afe;
    proxy_set_header Host $host;
  }

  location = /authentification { return 302 /authentification/; }
  location = /authentification/frontend { return 302 /authentification/; }
  location = /authentification/frontend/ { return 302 /authentification/; }

  # /webmap/... -> webmap frontend (prefix strip)
  location ^~ /webmap/ {
    rewrite ^/webmap/(.*)$ /$1 break;
    proxy_pass http://fe;
    proxy_set_header Host $host;
  }

  location = /webmap { return 302 /webmap/; }
  location = /webmap/frontend { return 302 /webmap/; }
  location = /webmap/frontend/ { return 302 /webmap/; }
}