upstream fe { server webmap_prod:5021; }
upstream db { server dashboard_prod:5023; }
upstream be {
  server backend:5031;
}
upstream abe {
  server authentification_backend:5032;
}
upstream afe { server authentification_frontend:5022; }

server {
  listen 80;

  location ^~ /backend/ {
    rewrite ^/backend/(.*)$ /$1 break;
    proxy_pass http://be;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-Id $request_id;
  }
  location = /backend { return 302 /backend/; }

  location ^~ /authentification/backend/ {
    rewrite ^/authentification/backend/(.+?)/?$ /$1 break;
    proxy_pass http://abe;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-Id $request_id;
  }
  location = /authentification/backend { return 302 /authentification/backend/; }


  # /authentification/... -> authentication frontend (prefix strip)
  location ^~ /authentification/ {
    rewrite ^/authentification/(.*)$ /$1 break;
    proxy_pass http://afe;
    proxy_set_header Host $host;
  }

  location = /authentification { return 302 /authentification/; }
  location = /authentification/frontend { return 302 /authentification/; }
  location = /authentification/frontend/ { return 302 /authentification/; }

  # /dashboard/... -> dashboard frontend
  location ^~ /dashboard/ {
    rewrite ^/dashboard/(.*)$ /$1 break;
    proxy_pass http://db;
    proxy_set_header Host $host;
  }

  location = /dashboard { return 302 /dashboard/; }

  # /webmap/... -> webmap frontend (prefix strip)
  location ^~ /webmap/ {
    rewrite ^/webmap/(.*)$ /$1 break;
    proxy_pass http://fe;
    proxy_set_header Host $host;
  }

  location = /webmap { return 302 /webmap/; }
}
